### ISSUE TITLE
关于APS数据集

### ISSUE THREAD

**Issue by lxd99** [Xovee/casflow#10]
同学你好！想请问下APS数据集的转发路径是如何构建的。如果一个user表示一个作者的话，那么转发路径的长度应该是只有1吧(每篇论文都是直接引用原始论文)。如果不是的话，那这个构建方式是和论文[1]一样的么。我看论文和仓库中没有介绍，所以特地来问下。期待作者解答！

[1] Cao Q, Shen H, Cen K, et al. Deephawkes: Bridging the gap between prediction and understanding of information cascades[C]//Proceedings of the 2017 ACM on Conference on Information and Knowledge Management. 2017: 1149-1158.

**Comment by Xovee** [comment]
感谢对我们论文的关注。

首先APS数据级联图以论文为节点而非作者。

其次论文 [1] 并没有公布APS数据集，因此我们自己处理了APS原数据集，可能与 [1] 不完全一致。

处理方法与 [1] 相同，以递归的形式处理citation list，向parent node添加边，最后构建成树（Tree graph）。

PS：这种方法应当视为最佳方案的一种妥协。不管是论文数据集，还是社交媒体数据集，真实的传播路径几乎不可能获得，而且受影响的路径显然不止一条。你也可以在已有的数据形式上尝试其他的构建方式，或许可以得到更好的结果。

**Comment by lxd99** [comment]
好的，感谢解答！

**Comment by Renjjjjjj** [comment]
> 感谢对我们论文的关注。
> 
> 首先APS数据级联图以论文为节点而非作者。
> 
> 其次论文 [1] 并没有公布APS数据集，因此我们自己处理了APS原数据集，可能与 [1] 不完全一致。
> 
> 处理方法与 [1] 相同，以递归的形式处理citation list，向parent node添加边，最后构建成树（Tree graph）。
> 
> PS：这种方法应当视为最佳方案的一种妥协。不管是论文数据集，还是社交媒体数据集，真实的传播路径几乎不可能获得，而且受影响的路径显然不止一条。你也可以在已有的数据形式上尝试其他的构建方式，或许可以得到更好的结果。

您好，我拜读了您的论文，想复现一下，但我没有找到APS的原始数据集，方便的话您能发我一份吗？感谢！innerB35674@163.com

**Comment by Xovee** [comment]
> > 感谢对我们论文的关注。
> > 首先APS数据级联图以论文为节点而非作者。
> > 其次论文 [1] 并没有公布APS数据集，因此我们自己处理了APS原数据集，可能与 [1] 不完全一致。
> > 处理方法与 [1] 相同，以递归的形式处理citation list，向parent node添加边，最后构建成树（Tree graph）。
> > PS：这种方法应当视为最佳方案的一种妥协。不管是论文数据集，还是社交媒体数据集，真实的传播路径几乎不可能获得，而且受影响的路径显然不止一条。你也可以在已有的数据形式上尝试其他的构建方式，或许可以得到更好的结果。
> 
> 您好，我拜读了您的论文，想复现一下，但我没有找到APS的原始数据集，方便的话您能发我一份吗？感谢！[innerB35674@163.com](mailto:innerB35674@163.com)

@Renjjjjjj 感谢你对我们论文的关注。APS原始数据集请见此链接：https://journals.aps.org/datasets

**Comment by Renjjjjjj** [comment]
感谢您的回复！我之前在https://journals.aps.org/datasets这上面申请了几次，但一直未得到回复，不知道您是否方便分享这个数据集，冒昧的再次询问。
















在 2024-06-19 20:48:13，"Xovee Xu" ***@***.***> 写道：

感谢对我们论文的关注。
首先APS数据级联图以论文为节点而非作者。
其次论文 [1] 并没有公布APS数据集，因此我们自己处理了APS原数据集，可能与 [1] 不完全一致。
处理方法与 [1] 相同，以递归的形式处理citation list，向parent node添加边，最后构建成树（Tree graph）。
PS：这种方法应当视为最佳方案的一种妥协。不管是论文数据集，还是社交媒体数据集，真实的传播路径几乎不可能获得，而且受影响的路径显然不止一条。你也可以在已有的数据形式上尝试其他的构建方式，或许可以得到更好的结果。

***@***.***

@Renjjjjjj 感谢你对我们论文的关注。APS原始数据集请见此链接：https://journals.aps.org/datasets
