### ISSUE TITLE
Seems not working in gene_emb.py file.

### ISSUE THREAD

**Issue by mauimoana** [Xovee/casflow#11]
It seems not working in gene_emb.py file.

![360截图20221007170614287](https://user-images.githubusercontent.com/77086328/194519278-9ade4257-c59b-4ff7-8006-a8c879571bb8.jpg)

**Comment by Xovee** [comment]
I'm so sorry I accidently commented the global embedding generating code (2 lines at 235 and 236) in `gene_cas.py`. You can uncommented the codes and re-run `gene_cas.py`. 

Thank you for pointing out this error.

**Comment by mauimoana** [comment]
Hey， it's my pleasure. Your codes and a series of cascading prediction works are really wonderful jobs.

**Comment by Xovee** [comment]
> Hey， it's my pleasure. Your codes and a series of cascading prediction works are really wonderful jobs.

Its really encouraging me. Thank you and have a good day!
