### ISSUE TITLE
Cascade classification

### ISSUE THREAD

**Issue by mauimoana** [Xovee/casflow#12]
Hey, I was wondering is this project, or your any other project in github, could handle the viral cascade prediction (classification problem), which is usually seen as an easier problem compared with the regression ones. 

Thanks for your time.

**Comment by Xovee** [comment]
Most of the cascade learning methods can be easily transformed into the viral classification ones (modifying the labels and the last network layers). I also conducted a cascade outbreak prediction in my CCGL paper (link: [github.com/Xovee/ccgl](http://github.com/Xovee/ccgl)). Another (early) paper that you can refer is: Cascading Outbreak Prediction in Networks: A Data-Driven Approach. KDD 2013. You can find related works from the citations of this paper. 

Hope it helps.

**Comment by mauimoana** [comment]
Thanks for your reply. It helps me a lot. 

Wish you have a good day.
