### ISSUE TITLE
关于twitter数据集

### ISSUE THREAD

**Issue by XgSuen** [Xovee/casflow#5]
请问大佬，Twitter数据集每条级联的源用户id为啥一直是-1，这不会对全局图的构建产生影响嘛，就像是所有的级联都是一个用户产生的感觉，希望大佬解答一下。大佬论文图表做的非常漂亮，值得学习哈哈

**Comment by Xovee** [comment]
谢谢夸奖！

首先说明一下数据集这方面的问题。因为社交网络平台的隐私等各种问题，所以数据集非常难找，带有转发路径的高质量数据集就更少了。之前很多公开的Twitter数据集好像都因为Twitter平台的政策陆续删除了（包括本文使用的Twitter数据集，它的公开下载地址已经无法访问了）。

然后本文的Twitter Cascade属于是Hashtag cascade。也就是说，我们建模的Information Item是#Hashtag#。`-1/u1`代表`u1`的tweet使用了该Hashtag，`-1/u1/u2`表示`u2`转发了`u1`的tweet。所以一个information cascade里包含多个子cascade。该cascade的popularity即所有子cascade的总转发数。

使用`-1`构建全局图是让数据集里的所有node都可以连接起来，算一种折中的方式吧（毕竟拿不到真实的全量的social network，如果是工业界使用自己的数据，当然不存在这个问题，本文算作一个初步尝试）。把`-1`换做每个hashtag cascade的`unique_id`，然后将这些`unique_id`连结到某个点（e.g., `-1`），或许可以减轻对全局图的影响。

非常感谢对我们论文的关注！

**Comment by Xovee** [comment]
@foreversunx 
友情提示：昨天刚更新了代码，可以在新的tensorflow版本下运行，你可以试试看呢~

**Comment by XgSuen** [comment]
> 谢谢夸奖！
> 
> 首先说明一下数据集这方面的问题。因为社交网络平台的隐私等各种问题，所以数据集非常难找，带有转发路径的高质量数据集就更少了。之前很多公开的Twitter数据集好像都因为Twitter平台的政策陆续删除了（包括本文使用的Twitter数据集，它的公开下载地址已经无法访问了）。
> 
> 然后本文的Twitter Cascade属于是Hashtag cascade。也就是说，我们建模的Information Item是#Hashtag#。`-1/u1`代表`u1`的tweet使用了该Hashtag，`-1/u1/u2`表示`u2`转发了`u1`的tweet。所以一个information cascade里包含多个子cascade。该cascade的popularity即所有子cascade的总转发数。
> 
> 使用`-1`构建全局图是让数据集里的所有node都可以连接起来，算一种折中的方式吧（毕竟拿不到真实的全量的social network，如果是工业界使用自己的数据，当然不存在这个问题，本文算作一个初步尝试）。把`-1`换做每个hashtag cascade的`unique_id`，然后将这些`unique_id`连结到某个点（e.g., `-1`），或许可以减轻对全局图的影响。
> 
> 非常感谢对我们论文的关注！

那是不是我将每个cascade的hashtag都设置一个唯一的id，即看作是类似weibo那样的源用户id，以此来构造每个cascade的cascade graph也是合适的呢？

**Comment by Xovee** [comment]
@foreversunx 
应该可以。构建cascade graph的过程不受这个id的影响，因为不同的cascade之间是独立的。

**Comment by XgSuen** [comment]
嗷嗷，谢谢大佬的耐心解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xovee ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 上午10:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xovee/casflow] 关于twitter数据集 (Issue #5)





 
@foreversunx
 应该可以。构建cascade graph的过程不受这个id的影响，因为不同的cascade之间是独立的。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
